USE NCU_BDD;

DELETE FROM Langues;

INSERT INTO Langues (code, libelle) VALUES
    ("FR", "Français"),
    ("EN", "Englais"),
    ("DE", "Allemand"),
    ("LA", "Latin"),
    ("ES", "Espagnol"),
    ("ZH", "Mandarin"),
    ("JA", "Japonais"),
    ("KO", "Coréen"),
    ("EO", "Esperanto"),
    ("HU", "Hongrois"),
    ("PL", "Polonais"),
    ("PT", "Portugais"),
    ("SV", "Suédois"),
    ("AF", "Afrikaans"),
    ("ZU", "Zoulou"),
    ("FI", "Finnois"),
    ("RU", "Russe"),
    ("AR", "Arabe"),
    ("HI", "Hindi"),
    ("BN", "Bengali"),
    ("TE", "Tégoulou"),
    ("SAT", "Santali"),
    ("ID", "Indonésien"),
    ("UK", "Ukrainien"),
    ("TY", "Tahitien"),
    ("IT", "Italien"),
    ("BR", "Breton"),
    ("DA", "Danois"),
    ("YUE", "Cantonais"),
    ("HT", "Créole"),
    ("LN", "Lingala"),
    ("NL", "Néerlandais"),
    ("RM", "Romanche"),
    ("TR", "Turc"),
    ("NO", "Norvégien"),
    ("LO", "Lao"),
    ("EL", "Grec"),
    ("PS", "Pachto"),
    ("PRS", "Dari"),
    ("BM", "Bambara"),
    ("GD", "Gaélique"),
    ("GA", "Irlandais"),
    ("IS", "Islandais"),
    ("EKK", "Estonien"),
    ("FA", "Persan"),
    ("RO", "Roumain"),
    ("NA", "Nauruan"),
    ("SO", "Somali"),
    ("GRC", "Grec Ancien"),
    ("CO", "Corse"),
    ("SR", "Serbe"),
    ("LT", "Lithuanien"),
    ("RHG", "Rohingya"),
    ("MY", "Birman"),
    ("KK", "Kazakh"),
    ("SW", "Swahili"),
    ("MI", "Maori"),
    ("PRS", "Dari"),
    ("PS", "Pachto"),
    ("LS", "Langue des signes"),
    ("PON", "Pohnpei"),
    ("BG", "Bulgare"),
    ("VI", "Vietnamien"),
    ("WO", "Wolof"),
    ("FF", "Peul"),
    ("BI", "Bichelamar"),
    ("ZGH", "Amazighe"),
    ("UR", "Ourdou"),
    ("VLS", "Flamand"),
    ("KM", "Khmer"),
    ("HE", "Hébreu"),
    ("YI", "Yiddish"),
    ("Mn", "Mongol"),
    ("PAP", "Papiamento"),
    ("LB", "Luxembourgeois"),
    ("LN", "Lingala"),
    ("KU", "Kurde")

;